.TH ADS-CATCHER-UNLOCKER 1
.SH NAME
ads-catcher-unlocker \- ads catcher for pi-hole
.SH SYNOPSIS
.B ads-catcher-unlocker
.SH DESCRIPTION
.B ads-catcher-unlocker
This tool monitors server requests (throught pihole logs) to detect \
if your main video is blocked by an extreme filtering. If your are in \
this case, it will unlock main video.
.SH OPTIONS
.TP
.BR 
no option

