#!/bin/sh

set -e

echo "Removing previous crontab entry..."
sed -i '/ads-catcher/d' /etc/crontab

echo "Adding crontab entry..."
echo "*/10 * * * * root /usr/bin/ads-catcher > /var/log/ads-catcher.log 2>&1" >> /etc/crontab

