#!/bin/sh
##############################################################################
# PEB <pebdev@lavache.com>
# 2019.04.14
##############################################################################
# Copyright (C) 2019
# This file is copyright under the latest version of the EUPL.
# Please see https://joinup.ec.europa.eu/collection/eupl for your rights
# under this license.
##############################################################################


# Launch unlocker script
ads-catcher-unlocker > /var/log/ads-catcher-unlocker.log 2>&1 &

# Launch blacklister script every 10 minutes
while true
do
  ads-catcher-blacklister > /var/log/ads-catcher-blacklister.log 2>&1
  sleep 10000
done

