.TH ADS-CATCHER 1
.SH NAME
ads-catcher \- ads catcher for pi-hole
.SH SYNOPSIS
.B ads-catcher.sh
.SH DESCRIPTION
.B ads-catcher
This tool scans pi-hole logfiles to find address of ads servers. \
It updates pi-hole blacklist automatically after a scan.
.SH OPTIONS
.TP
.BR \-a
Read all pihole logs (useful for the first launch)
.TP
.BR \-h
Display this help

